# Generated by Django 5.2.12 on 2026-03-16 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionbatch',
            name='name',
            field=models.CharField(default='Prediction Batch 20260316', max_length=200),
        ),
    ]
